### ISSUE TITLE
Add 'AddCustomEventAtEnd' interface

### ISSUE THREAD

**Issue by doggan** [Elendow/UnitySimpleSpriteAnimationPlugin#18]
Add `SpriteAnimatorEvent AddCustomEventAtEnd(string animation)` interface to BaseAnimator, which adds an event to the last frame of the specified animation. This eliminates having to specify the frame number when adding events to the end of an animation (which is a common use case).

**Comment by Elendow** [comment]
Hi Doggan!

Good idea, I'll add this 👍 Thanks for the feedback!!
